spring:
  datasource:
    url: jdbc:postgresql://localhost:2204/postgres
    username: krya
    password: P@ssword123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
